# Generated by Django 4.2 on 2023-05-25 18:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('catchTitle', models.CharField(max_length=50, verbose_name='Catch Title')),
                ('content', ckeditor.fields.RichTextField()),
                ('GeographicalLocation', models.CharField(max_length=50, verbose_name='Geographical Location')),
                ('clientNumMax', models.IntegerField(null=True, verbose_name='Max Clients')),
                ('popularity', models.IntegerField()),
                ('duration', models.IntegerField(default=0)),
                ('time_period', models.CharField(blank=True, choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months')], max_length=30, null=True)),
                ('food', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('sleepOrganisation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Sleep Organisation')),
                ('dates', models.DateField(blank=True, null=True, verbose_name='Dates from')),
                ('to', models.DateField(blank=True, null=True, verbose_name='To')),
                ('pricing', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
