# Generated by Django 4.2 on 2023-07-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="popularity",
        ),
    ]
