# Generated by Django 4.2 on 2023-08-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0002_remove_announcement_popularity"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="photos",
            field=models.ImageField(
                blank=True, null=True, upload_to="announcement/announcement_photos/"
            ),
        ),
    ]
