# Generated by Django 4.2 on 2023-08-09 19:11

import announcement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0004_alter_announcement_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="photos",
        ),
        migrations.CreateModel(
            name="AnnouncementPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=announcement.models.announcement_photos_directory_path
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_gallery",
                        to="announcement.announcement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announcement",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="announcements",
                to="announcement.announcementphoto",
            ),
        ),
    ]
