# Generated by Django 4.2 on 2023-08-09 19:15

import announcement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0005_remove_announcement_photos_announcementphoto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="photos",
        ),
        migrations.DeleteModel(
            name="AnnouncementPhoto",
        ),
        migrations.AddField(
            model_name="announcement",
            name="photos",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=announcement.models.announcement_photos_directory_path,
            ),
        ),
    ]
