# Generated by Django 4.2 on 2023-08-09 20:01

import announcement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "announcement",
            "0006_remove_announcement_photos_delete_announcementphoto_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="photos",
        ),
        migrations.CreateModel(
            name="AnnouncementPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=announcement.models.announcement_photos_directory_path
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcement_photos",
                        to="announcement.announcement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announcement",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                related_name="announcements",
                to="announcement.announcementphoto",
            ),
        ),
    ]
