# Generated by Django 4.2 on 2023-08-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcement", "0007_remove_announcement_photos_announcementphoto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="photos",
        ),
    ]
