# file created: 2023-02-10 23:14:58.086464

# this files has been generated by XXXXXXXX.XXX  Please do not change manually
# author: Next Level Sense

# Available functions:
#    render - replacement for django render function
#    path - replacement for django path function. please use with * when replacing in urls.py
#    supported_languages - list that contains all available languages for this site
# Functions to be used in django templates:
#    languageReferences - create 'alternate' language references for SEO.
#        put it inside of the <head> section of the page in format {{languageReferences|safe}}
#    lang - current language. Used mostly in <html lang="{{lang}}">
#    languageMenu - adding language selection for your page. Format: {{languageMenu|safe}}
#    <<link variables>> - create linking to correct language link. 
#    usage:
#    for translated pages change {% url "my_page" %}
#    to name without quotes:     {% url my_page %}


supported_languages = ['fr', 'de', 'pl', 'en']

def translation_dictionary(lang):
    if lang == 'fr': return {
        'navigationbar_nav':'''Profil''',
        'navigationbar_nav':'''Publier une formation''',
        'navigationbar_nav':'''Rechercher une annonce''',
        'navigationbar_nav':'''Langue''',
        'navigationbar_nav':'''Accueil''',
        'navigationbar_nav':'''Boutique''',
        'navigationbar_nav':'''Calendrier''',
        'navigationbar_nav':'''Contact''',
        'navigationbar_nav':'''Savoir plus''',
        'announcement_subject':'''Votre stage notre objectif''',
        'announcement_title':'''Walkirii vous accompagne dans votre processus de formation''',
        'announcement_info':'''Bienvenue! Chez Walkirii, notre plateforme a pour but de vous permettre de poster vos propositions de formations en tout genres au sein de la Pologne ! Que ce soit en maniement des armes, training médical, tutoriels de survie, nous vous proposons de poster toutes les informations pertinentes dans le formulaire ci-dessous.''',
        'announcement_name':'''Name''',
        'announcement_name':'''Instructor name *''',
        'announcement_value':'''User ID ''',
        'announcement_value':'''Enter id''',
        'announcement_title':'''Title of the training session''',
        'announcement_title':'''Enter title *''',
        'announcement_title':'''Catch Title''',
        'announcement_description':'''Brief description''',
        'announcement_description':'''Exhaustiv description''',
        'announcement_info':'''Hover to open field''',
        'announcement_description':'''Description *''',
        'announcement_info':'''Geographical location''',
        'announcement_info':'''Location *''',
        'announcement_info':'''Submit''',
        'announcement_value':'''Client numbers''',
        'announcement_value':'''Max clients *''',
        'announcement_value':'''Popularity''',
        'announcement_value':'''Duration''',
        'announcement_value':'''Hours''',
        'announcement_value':'''Days''',
        'announcement_value':'''Weeks''',
        'announcement_value':'''Months''',
        'announcement_value':'''Food''',
        'announcement_bool':'''Yes''',
        'announcement_bool':'''No''',
        'announcement_info':'''Sleep organisation''',
        'announcement_bool':'''Yes''',
        'announcement_bool':'''No''',
        'announcement_value':'''Dates''',
        'announcement_value':'''to''',
        'announcement_value':'''Pricing *''',
        'announcement_value':'''Euros''',
        'announcement_info':'''En savoir plus''',
        'announcement_info':'''Conditions de vente''',
        'announcement_info':'''FAQ''',
        'announcement_info':'''Contact''',
        }
    if lang == 'de': return {
        'navigationbar_nav':'''Profil''',
        'navigationbar_nav':'''Veröffentlichen''',
        'navigationbar_nav':'''Suche nach einer Anzeige''',
        'navigationbar_nav':'''Sprache''',
        'navigationbar_nav':'''Willkommen''',
        'navigationbar_nav':'''Geschäft''',
        'navigationbar_nav':'''Kalender''',
        'navigationbar_nav':'''Kontakt''',
        'navigationbar_nav':'''Mehr wissen''',
        'announcement_subject':'''Ihr Praktikum ist unser Ziel''',
        'announcement_title':'''Walkirii unterstützt Sie in Ihrem Trainingsprozess''',
        'announcement_info':'''Willkommen! Bei Walkirii zielt unsere Plattform darauf ab, Ihre Trainingsvorschläge in allen Arten in Polen zu veröffentlichen! Egal, ob Sie Waffen, medizinisches Training, Überlebens -Tutorials behandeln, wir laden Sie ein, alle relevanten Informationen in der folgenden Form zu veröffentlichen.''',
        'announcement_name':'''Name''',
        'announcement_name':'''Ausbildername *''',
        'announcement_value':'''Benutzer-ID''',
        'announcement_value':'''ID eingeben''',
        'announcement_title':'''Titel der Trainingseinheit''',
        'announcement_title':'''Titel * eingeben *''',
        'announcement_title':'''Fang Titel''',
        'announcement_description':'''Kurze Beschreibung''',
        'announcement_description':'''Auslassvision Beschreibung''',
        'announcement_info':'''Schweben, um Feld zu öffnen''',
        'announcement_description':'''Beschreibung *''',
        'announcement_info':'''Geografische Position''',
        'announcement_info':'''Standort *''',
        'announcement_info':'''Einreichen''',
        'announcement_value':'''Kundennummern''',
        'announcement_value':'''Max Clients *''',
        'announcement_value':'''Popularität''',
        'announcement_value':'''Dauer''',
        'announcement_value':'''Std''',
        'announcement_value':'''Tage''',
        'announcement_value':'''Wochen''',
        'announcement_value':'''Monate''',
        'announcement_value':'''Essen''',
        'announcement_bool':'''Ja''',
        'announcement_bool':'''NEIN''',
        'announcement_info':'''Schlaforganisation''',
        'announcement_bool':'''Ja''',
        'announcement_bool':'''NEIN''',
        'announcement_value':'''Termine''',
        'announcement_value':'''Zu''',
        'announcement_value':'''Preisgestaltung *''',
        'announcement_value':'''Euro''',
        'announcement_info':'''Erfahren Sie mehr''',
        'announcement_info':'''Verkaufsbedingungen''',
        'announcement_info':'''FAQ''',
        'announcement_info':'''Kontakt''',
        }
    if lang == 'pl': return {
        'navigationbar_nav':'''Profil''',
        'navigationbar_nav':'''Publier une formation''',
        'navigationbar_nav':'''Rechercher une annonce''',
        'navigationbar_nav':'''Langue''',
        'navigationbar_nav':'''Accueil''',
        'navigationbar_nav':'''Boutique''',
        'navigationbar_nav':'''Calendrier''',
        'navigationbar_nav':'''Contact''',
        'navigationbar_nav':'''Savoir plus''',
        'announcement_subject':'''Votre stage notre objectif''',
        'announcement_title':'''Walkirii vous accompagne dans votre processus de formation''',
        'announcement_info':'''Bienvenue! Chez Walkirii, notre plateforme a pour but de vous permettre de poster vos propositions de formations en tout genres au sein de la Pologne ! Que ce soit en maniement des armes, training médical, tutoriels de survie, nous vous proposons de poster toutes les informations pertinentes dans le formulaire ci-dessous.''',
        'announcement_name':'''Nom''',
        'announcement_name':'''Nom de l'instructeur *''',
        'announcement_value':'''ID de l'utilisateur''',
        'announcement_value':'''Entrez ID''',
        'announcement_title':'''Titre de la session de formation''',
        'announcement_title':'''Entrez le titre *''',
        'announcement_title':'''Titre de capture''',
        'announcement_description':'''Brève description''',
        'announcement_description':'''Description épuistiv''',
        'announcement_info':'''Planer pour ouvrir le terrain''',
        'announcement_description':'''Description *''',
        'announcement_info':'''Localisation géographique''',
        'announcement_info':'''Emplacement *''',
        'announcement_info':'''Soumettre''',
        'announcement_value':'''Numéros de client''',
        'announcement_value':'''Les clients de Max *''',
        'announcement_value':'''Popularité''',
        'announcement_value':'''Durée''',
        'announcement_value':'''Heures''',
        'announcement_value':'''Jours''',
        'announcement_value':'''Semaines''',
        'announcement_value':'''Mois''',
        'announcement_value':'''Nourriture''',
        'announcement_bool':'''Oui''',
        'announcement_bool':'''Non''',
        'announcement_info':'''Organisation de sommeil''',
        'announcement_bool':'''Oui''',
        'announcement_bool':'''Non''',
        'announcement_value':'''Rendez-vous''',
        'announcement_value':'''pour''',
        'announcement_value':'''Prix ​​*''',
        'announcement_value':'''Euros''',
        'announcement_info':'''En savoir plus''',
        'announcement_info':'''Conditions de Vente''',
        'announcement_info':'''FAQ''',
        'announcement_info':'''Contact''',
        }
    if lang == 'en': return {
        'navigationbar_nav':'''Profil''',
        'navigationbar_nav':'''Publikować''',
        'navigationbar_nav':'''Wyszukaj reklamę''',
        'navigationbar_nav':'''Język''',
        'navigationbar_nav':'''Powitanie''',
        'navigationbar_nav':'''Sklep''',
        'navigationbar_nav':'''Kalendarz''',
        'navigationbar_nav':'''Kontakt''',
        'navigationbar_nav':'''Wiedzieć więcej''',
        'announcement_subject':'''Twój staż nasz cel''',
        'announcement_title':'''Walkirii wspiera Cię w procesie szkoleniowym''',
        'announcement_info':'''Powitanie! Nasza platforma na Walkirii ma na celu umożliwienie Ci publikowania propozycji treningów wszelkiego rodzaju w Polsce! Niezależnie od tego, czy chodzi o obchodzenie się z bronią, szkolenie medyczne czy samouczki dotyczące przetrwania, zachęcamy do opublikowania wszystkich istotnych informacji w poniższym formularzu.''',
        'announcement_name':'''Nazwa''',
        'announcement_name':'''Nazwa instruktora *''',
        'announcement_value':'''Identyfikator użytkownika''',
        'announcement_value':'''Wprowadź identyfikator''',
        'announcement_title':'''Tytuł sesji treningowej''',
        'announcement_title':'''Wprowadź tytuł *''',
        'announcement_title':'''Złap tytuł''',
        'announcement_description':'''Krótki opis''',
        'announcement_description':'''Opis wydechu''',
        'announcement_info':'''Wathe to Otwarte pole''',
        'announcement_description':'''Opis *''',
        'announcement_info':'''Położenie geograficzne''',
        'announcement_info':'''Lokalizacja *''',
        'announcement_info':'''Składać''',
        'announcement_value':'''Numery klientów''',
        'announcement_value':'''Max klienci *''',
        'announcement_value':'''Popularność''',
        'announcement_value':'''Czas trwania''',
        'announcement_value':'''godziny''',
        'announcement_value':'''Dni''',
        'announcement_value':'''Tygodnie''',
        'announcement_value':'''Miesiące''',
        'announcement_value':'''Żywność''',
        'announcement_bool':'''Tak''',
        'announcement_bool':'''NIE''',
        'announcement_info':'''Organizacja snu''',
        'announcement_bool':'''Tak''',
        'announcement_bool':'''NIE''',
        'announcement_value':'''Daktyle''',
        'announcement_value':'''Do''',
        'announcement_value':'''Cennik *''',
        'announcement_value':'''Euro''',
        'announcement_info':'''Ucz się więcej''',
        'announcement_info':'''Warunki sprzedaży''',
        'announcement_info':'''FAQ''',
        'announcement_info':'''Kontakt''',
        }


def detectLanguage(request):
    languageDetected = supported_languages[0]
    lastPath = request.path.split('/')[-1]
    if lastPath in supported_languages[1:]:
        languageDetected = lastPath
    return languageDetected


from django.urls import path as org_path
def path(route, view, kwargs=None, name=None):
    if route == '':
        return [org_path('', view, kwargs, name),org_path('de', view, kwargs, name+'_de'),org_path('pl', view, kwargs, name+'_pl'),org_path('en', view, kwargs, name+'_en'),]
    if route[-1] == '/': route=route[:-1]
    return [org_path(route, view, kwargs, name),org_path(route+'/de', view, kwargs, name+'_de'),org_path(route+'/pl', view, kwargs, name+'_pl'),org_path(route+'/en', view, kwargs, name+'_en'),]


def langRef(path_ref):
    last=path_ref.split('/')[-1]
    if last in supported_languages:
        path_ref=path_ref[:-len(last)-1]
    result='<link rel="alternate" hreflang="fr" href="'+addLinks(path_ref,'')+'" />\n'
    result+='<link rel="alternate" hreflang="de" href="'+addLinks(path_ref,'de')+'" />\n'
    result+='<link rel="alternate" hreflang="pl" href="'+addLinks(path_ref,'pl')+'" />\n'
    result+='<link rel="alternate" hreflang="en" href="'+addLinks(path_ref,'en')+'" />\n'
    result+='<link rel="alternate" hreflang="x-default" href="'+addLinks(path_ref,'')+'" />\n'
    return result


from django.urls import get_resolver
def translatedLinks(lang):
    names=[]
    for i in get_resolver().url_patterns:
        if hasattr(i, 'name'):
            if i.name:
                names.append(i.name)
    result = {}
    if lang == supported_languages[0]:
        for i in names:
            if i[-3:] not in ['_de', '_pl', '_en'] and names.count(i+'_de'):
                result.update({i:i})
        return result
    for i in names:
        if names.count(i+'_'+lang):
            result.update({i:i+'_'+lang})
    return result


def languageMenu(path, lang):
    selected = [' ', ' ', ' ', ' ']
    selected[supported_languages.index(lang)]=' selected '
    if supported_languages.index(lang):
        path=path[:-3]
    result = '<select id="languageMenu" onchange="window.location = this.value;">'
    if path == '/': path = ''
    if path =='':
        result += '<option'+selected[0]+'value="/">French (Français)</option>'
    else:
        result += '<option'+selected[0]+'value="' + path +'">French (Français)</option>'
    result += '<option'+selected[1]+'value="' + path +'/de">German (Deutsch)</option>'
    result += '<option'+selected[2]+'value="' + path +'/pl">Polish (Polski)</option>'
    result += '<option'+selected[3]+'value="' + path +'/en">English (English)</option>'
    result += '</select>'
    return result


from django.shortcuts import render as org_render
def render(request, template_name, context=None, *args, **kwargs):
    lang=detectLanguage(request)
    if context == None:
        context={}
    return org_render(request, template_name, {**context,
                                                **translation_dictionary(lang),
                                                'lang':lang,
                                                'languageReferences':langRef(request.build_absolute_uri()),
                                                'languageMenu':languageMenu(request.path, lang),
                                                'candyLink':translatedLinks(lang),
                                                }, *args, **kwargs)


def addLinks(*args):
    result=''
    for i in args:
        if result and result[-1]=='/':result=result[:-1]
        if i and i[-1]=='/':i=i[:-1]
        if i and i[0]=='/':i=i[1:]
        if result and i: result+='/'
        result+=i
    return result


def provideSitemap(request, add_pages=[], remove_pages=[]):
    from django.http import HttpResponse
    result='<?xml version="1.0" encoding="UTF-8"?>'+'\n'
    result+='<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+'\n'
    domain= request.build_absolute_uri()
    domain=domain.split('/')[0]+'//'+domain.split('/')[2]+'/'
    paths = []
    for i in get_resolver().url_patterns:
        if str(type(i))=="<class 'django.urls.resolvers.URLPattern'>":
            route=i.pattern._route
            route=route.split('<')[0]
            if not route == 'sitemap.xml':
                paths.append(addLinks(domain,route))
    paths+=add_pages
    paths=list(dict.fromkeys(paths))
    for route in paths:
        if route not in remove_pages:
            result+='<url>'+'\n'
            result+='<loc>'+route+'</loc>'+'\n'
            result+='</url>'+'\n'
    result+='</urlset>'
    result= result.encode('utf-8')
    return HttpResponse(result, content_type='application/xml; charset=utf-8')


def sitemap(add_pages=[], remove_pages=[]):
    return [org_path('sitemap.xml', provideSitemap,{'add_pages' :add_pages,'remove_pages': remove_pages})]


