# Generated by Django 4.2 on 2023-07-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_account_presentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_formation",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Latest Animated Training",
            ),
        ),
    ]
