# Generated by Django 4.2 on 2023-07-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_account_last_formation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.ImageField(default="media/avatar.jpg", upload_to="avatars/"),
        ),
    ]
