# Generated by Django 4.2 on 2023-08-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_account_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="Birthday"),
        ),
    ]
