# Generated by Django 4.2 on 2023-08-03 17:09

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_account_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatar.jpg",
                null=True,
                upload_to=user.models.user_directory_path,
            ),
        ),
    ]
